### ISSUE TITLE
Relate Paper

### ISSUE THREAD

**Issue by chengwei0427** [davidskdds/DMSA_LiDAR_SLAM#1]
Hi, @davidskdds 
Nice work! Is there a relate paper?

**Comment by davidskdds** [comment]
Hello @chengwei0427 ,

thank you for the feedback!
I have now added a [link](https://arxiv.org/abs/2402.19044) to the paper in the README.md

**Comment by chengwei0427** [comment]
Thanks. Problem solved.
In addition, if there are some videos about the presentation of the paper, it will be more perfect.

**Comment by chengwei0427** [comment]
Hi, @chengwei0427 
Can you tell me which version of pcl you are using? 
pcl is 1.8 in my computer,there is a error about `octree.leaf_depth_begin()`.


There is no `leaf_depth_begin` in pcl1.8, and here I modify to use `leaf_begin` instead.The results are as follows
![2024-03-07 16-02-30屏幕截图](https://github.com/davidskdds/DMSA_LiDAR_SLAM/assets/20199999/4b89d4ec-2d0e-4ba3-a61d-9b8aaae27b26)

**Comment by davidskdds** [comment]
Hello @chengwei0427 ,
I am using pcl version **1.10.0**.
Replacing "leaf_depth_begin()" by "leaf_begin()" should be possible and not lead to errors.

In the screenshot you sent, I can see a discontinuity in the red trajectory in the lower center of the image. I assume you are asking because of that. Unfortunately, I do not see any LiDAR points in the lower area to draw conclusions about the cause.

Which LiDAR sensor are you using? Is an IMU used?
Do you have a rviz screenshot with the white map points (topic: "/dmsa_slam/map", is displayed with the standard rviz settings)?

A "dirty" fix, which does not solve the cause of the problem, would probably be to deactivate keyframe optimization.
This is done by setting the variable "optimize_sliding_window_keyframes" in "config/slam_settings.yaml" to "false".

Nevertheless, I look forward to more information to find the root cause.

**Comment by chengwei0427** [comment]
Hi, @davidskdds 
Thanks for your patient  reply.
Now I can now run the project in ubuntu18.04. 
In the screenshot, I just test with a VLP16 and without imu, and it works well.
In addition, I also tested an ouster+IMU data and it worked very well.
Thank you for your nice work. I will study it more deeply in the next step.
If there are any questions in the in-depth study of your work, I will re-open an issue to communicate with you.
Thanks again.
