### ISSUE TITLE
What are requirements on the init poses of scans to be optimized?

### ISSUE THREAD

**Issue by deliangye** [davidskdds/DMSA_LiDAR_SLAM#5]
Hey, thanks for sharing your great work, but I have a question as the title, it seems the init poses of scans to be optimized must be good enough, right? otherwise points in a landmark might not come from the same area in the real environment,  which may cause the optimizer can not converge or stuck a local minimum, right?

-Deliang

**Comment by davidskdds** [comment]
Hello Deliang,

yes, you are right, the basic DMSA proposed in the paper needs an coarse initial guess for optimization.
The basic DMSA is used for keyframe optimization within this package. Since we already have a relatively accurate pose estimation for keyframes, this condition is fulfilled.

For sliding window continuous DMSA, IMU data is used to obtain an initial guess.
If no IMU is used, there is no initial guess for the sliding window continuous DMSA optimization. In this case, the software only works for slow to medium speed changes and rotation rates, whereas with IMU accurate estimates are possible even for high frequency movements.

I hope this answers your question.

Best regards
David

**Comment by deliangye** [comment]
David, thanks for clarification!
