### ISSUE TITLE
The significance of the Cubic Hermitian split

### ISSUE THREAD

**Issue by wuming122333** [davidskdds/DMSA_LiDAR_SLAM#6]
Thank you for open-source this amazing work. I'm a bit confused. May I ask why we need to perform Cubic Hermitian spline on the attitude trajectory? How much does Cubic Hermitian spline improve the accuracy of the system

**Comment by davidskdds** [comment]
Hello @wuming122333 ,
thanks for your interest.

Cubic Hermitian spline interpolation was only used for the translational part of the trajectory.
For the orientational part (attitude) [slerp](https://en.wikipedia.org/wiki/Slerp) is used.
As noted in the README here, instead of Cubic Hermitian splines in the open source code [Barycentric Rational Interpolation](https://live.boost.org/doc/libs/1_72_0/libs/math/doc/html/math_toolkit/barycentric.html) is used for the translational part (due to the license conditions).

The type of interpolation can significantly influence the quality of the estimated trajectory in the case of high-frequency movements. Therefore, this type of interpolation makes sense for handheld systems, but is less important for data from car roof-mounted scanners.

Best regards
David
